### ISSUE TITLE
DfuSe mode not working

### ISSUE THREAD

**Issue by ho-ho-ho** [IntergatedCircuits/DfuBootloader#5]
I've tried to integrate this bootloader with my STM32F303CC and it's working fine in the non-DfuSe mode. But if I try to enable it, there's quite a few problems.

First of all, the Makefile has an error:
```
ifdef DFUSE
C_DEFS += \
-DUSBD_DFU_ST_EXTENSION=$(DFUSE) \
-DFLASH_ERASE_TIME_ms=$(ERASE_MS) \
-DSE_FLASH_DESC_STR=DESC_STR
else
C_DEFS += -DFLASH_TOTAL_ERASE_TIME_ms=$(TOTAL_ERASE_MS)
endif
```
Notice how in the line `-DSE_FLASH_DESC_STR=DESC_STR` the `DESC_STR` is actually just a string literal, not a variable, e.g. `$(DESC_STR)`. This leads to some compile errors.

After fixing that, it compiles fine and ST's DfuSe tool even picks up the device and all parameters (like flash sections). But as soon as I try to download or upload a firmware, there's this error:
```
$ ./DfuSeCommand.exe -c -d --fn test.dfu
1 Device(s) found :
Device [1]: STM Device in DFU Mode, having [1] alternate targets
 Duration: 00:00:00
Target 00: Error Code: Bad state machine in firmware
Target: 00
Error Code: Bad state machine in firmware
TransferSize: 1024
DFU State: STATE_DFU_DOWNLOAD_SYNC
DFU Status: STATUS_OK
Request: Get Status Request.
CurrentNBlock: 0x0000
CurrentLength: 0x0005
Percent: 0
```
looks like something is wrong with the DfuSe protocol implementation?

**Comment by benedekkupper** [comment]
Can you record the USB transactions somehow, or log them from the STM32? I'll look into the ST code as well and try to find what's different in the state machine, but some logs would definitely help. I cannot use the DfuSe myself anymore since I've updated to the CubeProgrammer, which installs an incompatible USB driver.

**Comment by ho-ho-ho** [comment]
Here we go, a Wireshark capture (if you prefer another format, just tell me :) ).
Around the timestamp of 21.5 I initiated the `./DfuSeCommand.exe -c -d --fn test.dfu` command.
[bootloader.zip](https://github.com/IntergatedCircuits/DfuBootloader/files/4297747/bootloader.zip)

**Comment by benedekkupper** [comment]
I have fixed this transition I believe, please give me feedback on the latest USBDevice master, I can't wait to hear what's the next bug you'll find :)

**Comment by ho-ho-ho** [comment]
Success!
```
$ ./DfuSeCommand.exe -c -d --fn test.dfu
1 Device(s) found :
Device [1]: STM Device in DFU Mode, having [1] alternate targets
Target 00: Upgrading - Download Phase (100)...Duration: 00:00:08
Upgrade successful !
```
The USBDevice master works like a charm! Thanks! No more bugs found for now 😉

**Comment by benedekkupper** [comment]
Great, thanks for the catch :)
