### ISSUE TITLE
hardfault occur M0(+) Core

### ISSUE THREAD

**Issue by aroerina** [IntergatedCircuits/DfuBootloader#6]
usbd_dfu.c
784: and 792:
itf->Address = (uint8_t*)(*(__packed uint32_t *)data);

This code is unaligned access; in the MCU with an M0(+) core, it is Fires a hardfault.

**Comment by benedekkupper** [comment]
Thanks for reporting this, can you check with the latest master again?

**Comment by aroerina** [comment]
Thanks for fixing the code.
I compiled it and tried it on an STM32F072CB and DfuSe.
It worked perfectly.
